### PR TITLE
Two minor typographical errors corrected

### PR DESCRIPTION
**Pull request by j-r-jones**
Corrected two minor typos:
* One of the subheadings had 'comamnd' instead of 'command' - now fixed
* Changed 'identify matrix' to 'identity matrix'

### CODE REVIEW

**Comment by florianschanda** [comment]
Isn't that the exact same request I already merged?

**Comment by j-r-jones** [comment]
I thought it had been merged, but github flagged it up as not having been done yet.  Confusing..

**Comment by florianschanda** [comment]
See https://github.com/florianschanda/miss_hit/commit/6ebe574dfff65a07c5f6a0c38eb8c3814623b8bb

**Comment by j-r-jones** [comment]
Thanks.  I'll ignore github on this one then.  I don't know why it thinks it hasn't happened.

**Pull request closed without merging**
