### PR TITLE
add zenodo badge and fix typo

### PR DESCRIPTION
**Pull request by Remi-Gau**
2 tiny changes while waiting for me to have more time to do some more substantial contributions. :smile: 

- [x] fix typo in 'the all seems fine message'
- [x] add a badge with the DOI zenodo

Do you want me to look into adding some badges giving the status of the github action ?

### CODE REVIEW

**Comment by Remi-Gau** [comment]
Another possible tiny thing I can try to add: a link in the doc to the github repo. I looked for it a couple of times and I suspect it would be nice to have it.

**Comment by florianschanda** [comment]
The link is in README.md, see the first link in section "Tools & Documentation".

**Comment by florianschanda** [comment]
I also fixed (type -> typo) in your commit message :D

**Comment by Remi-Gau** [comment]
> The link is in README.md, see the first link in section "Tools & Documentation".

Ha I did not explain myself clearly. Sorry.

I meant once you are on the doc website (https://florianschanda.github.io/miss_hit/) there is no obvious link on the landing page of the doc to link you back to the github repo.

**Comment by florianschanda** [comment]
That makes sense. Done.

**Pull request merged**
